name: CI Back-end
on: 
  push:
    branches:
      - 'main'
    paths: 
      - 'sgcmapi/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Compile/Test
        run: mvn compile test